/**
 * NLAMS - Policy Maker & Executive Oversight Permission Catalog
 * Defines RBAC definitions for Pillar 5: Policy Makers & Executive Analytics
 * Compliant with RFCTLARR Act 2013 (Sec 45, Sec 48, Sec 50)
 */

export const POLICY_MAKER_PERMISSIONS = {
  // Core Module View Permissions
  EXECUTIVE_OVERVIEW_VIEW: 'POLICY_MAKER_EXECUTIVE_OVERVIEW_VIEW',
  GIS_VIEW: 'POLICY_MAKER_GIS_VIEW',
  PIPELINE_VIEW: 'POLICY_MAKER_PIPELINE_VIEW',
  RISK_VIEW: 'POLICY_MAKER_RISK_VIEW',
  FINANCE_VIEW: 'POLICY_MAKER_FINANCE_VIEW',
  MEETINGS_VIEW: 'POLICY_MAKER_MEETINGS_VIEW',
  MOM_VIEW: 'POLICY_MAKER_MOM_VIEW',
  DIRECTIVES_VIEW: 'POLICY_MAKER_DIRECTIVES_VIEW',
  BOTTLENECK_VIEW: 'POLICY_MAKER_BOTTLENECK_VIEW',
  RR_VIEW: 'POLICY_MAKER_RR_VIEW',
  SOCIAL_AUDIT_VIEW: 'POLICY_MAKER_SOCIAL_AUDIT_VIEW',
  REPORTS_VIEW: 'POLICY_MAKER_REPORTS_VIEW',
  PROJECT_DETAILS_VIEW: 'POLICY_MAKER_PROJECT_DETAILS_VIEW',
  DOCUMENTS_VIEW: 'POLICY_MAKER_DOCUMENTS_VIEW',
  AUDIT_VIEW: 'POLICY_MAKER_AUDIT_VIEW',

  // Operational Sub-Action Permissions (Gated for Statutory Oversight)
  MEETING_CREATE: 'POLICY_MAKER_MEETING_CREATE',
  MOM_SIGN: 'POLICY_MAKER_MOM_SIGN',
  DIRECTIVE_ISSUE: 'POLICY_MAKER_DIRECTIVE_ISSUE',
  BOTTLENECK_ESCALATE: 'POLICY_MAKER_BOTTLENECK_ESCALATE',
  REPORT_EXPORT: 'POLICY_MAKER_REPORT_EXPORT',
  NOTE_ADD: 'POLICY_MAKER_NOTE_ADD'
};

export const COMMITTEE_ROLES = {
  APEX: {
    id: 'APEX',
    name: 'Apex Executive Bodies',
    title: 'NITI Aayog / PMO / Cabinet Secretariat / DoLR',
    legalBasis: 'Executive Government of India & State Oversight',
    scope: 'NATIONAL',
    badgeText: 'APEX EXECUTIVE',
    badgeColor: 'bg-purple-900/40 text-purple-200 border-purple-500/50',
    permissions: [
      POLICY_MAKER_PERMISSIONS.EXECUTIVE_OVERVIEW_VIEW,
      POLICY_MAKER_PERMISSIONS.GIS_VIEW,
      POLICY_MAKER_PERMISSIONS.PIPELINE_VIEW,
      POLICY_MAKER_PERMISSIONS.RISK_VIEW,
      POLICY_MAKER_PERMISSIONS.FINANCE_VIEW,
      POLICY_MAKER_PERMISSIONS.MEETINGS_VIEW,
      POLICY_MAKER_PERMISSIONS.MOM_VIEW,
      POLICY_MAKER_PERMISSIONS.DIRECTIVES_VIEW,
      POLICY_MAKER_PERMISSIONS.BOTTLENECK_VIEW,
      POLICY_MAKER_PERMISSIONS.RR_VIEW,
      POLICY_MAKER_PERMISSIONS.SOCIAL_AUDIT_VIEW,
      POLICY_MAKER_PERMISSIONS.REPORTS_VIEW,
      POLICY_MAKER_PERMISSIONS.PROJECT_DETAILS_VIEW,
      POLICY_MAKER_PERMISSIONS.DOCUMENTS_VIEW,
      POLICY_MAKER_PERMISSIONS.AUDIT_VIEW,
      POLICY_MAKER_PERMISSIONS.MEETING_CREATE,
      POLICY_MAKER_PERMISSIONS.MOM_SIGN,
      POLICY_MAKER_PERMISSIONS.DIRECTIVE_ISSUE,
      POLICY_MAKER_PERMISSIONS.BOTTLENECK_ESCALATE,
      POLICY_MAKER_PERMISSIONS.REPORT_EXPORT,
      POLICY_MAKER_PERMISSIONS.NOTE_ADD
    ]
  },
  NMC: {
    id: 'NMC',
    name: 'National Monitoring Committee',
    title: 'National Monitoring Committee (NMC)',
    legalBasis: 'RFCTLARR Act 2013, Section 48',
    scope: 'NATIONAL_INTERSTATE',
    badgeText: 'NMC MEMBER (SEC 48)',
    badgeColor: 'bg-blue-900/50 text-blue-200 border-blue-500/50',
    head: 'Secretary, Department of Land Resources (DoLR)',
    membersDescription: '18+ Central Ministry Representatives (Agriculture, Coal, Defence, MoEFCC, MoRTH, Railways, Power, NITI Aayog)',
    permissions: [
      POLICY_MAKER_PERMISSIONS.EXECUTIVE_OVERVIEW_VIEW,
      POLICY_MAKER_PERMISSIONS.GIS_VIEW,
      POLICY_MAKER_PERMISSIONS.PIPELINE_VIEW,
      POLICY_MAKER_PERMISSIONS.RISK_VIEW,
      POLICY_MAKER_PERMISSIONS.FINANCE_VIEW,
      POLICY_MAKER_PERMISSIONS.MEETINGS_VIEW,
      POLICY_MAKER_PERMISSIONS.MOM_VIEW,
      POLICY_MAKER_PERMISSIONS.DIRECTIVES_VIEW,
      POLICY_MAKER_PERMISSIONS.BOTTLENECK_VIEW,
      POLICY_MAKER_PERMISSIONS.RR_VIEW,
      POLICY_MAKER_PERMISSIONS.SOCIAL_AUDIT_VIEW,
      POLICY_MAKER_PERMISSIONS.REPORTS_VIEW,
      POLICY_MAKER_PERMISSIONS.PROJECT_DETAILS_VIEW,
      POLICY_MAKER_PERMISSIONS.DOCUMENTS_VIEW,
      POLICY_MAKER_PERMISSIONS.MOM_SIGN,
      POLICY_MAKER_PERMISSIONS.DIRECTIVE_ISSUE,
      POLICY_MAKER_PERMISSIONS.BOTTLENECK_ESCALATE,
      POLICY_MAKER_PERMISSIONS.REPORT_EXPORT,
      POLICY_MAKER_PERMISSIONS.NOTE_ADD
    ]
  },
  SMC: {
    id: 'SMC',
    name: 'State Monitoring Committee',
    title: 'State Monitoring Committee (SMC - Gujarat)',
    legalBasis: 'RFCTLARR Act 2013, Section 50',
    scope: 'STATE',
    defaultState: 'Gujarat',
    badgeText: 'SMC MEMBER (SEC 50)',
    badgeColor: 'bg-emerald-900/50 text-emerald-200 border-emerald-500/50',
    head: 'Chief Secretary, Govt of Gujarat',
    membersDescription: 'State Department Secretaries (Revenue, Finance, Forest, IT, IGR)',
    permissions: [
      POLICY_MAKER_PERMISSIONS.EXECUTIVE_OVERVIEW_VIEW,
      POLICY_MAKER_PERMISSIONS.GIS_VIEW,
      POLICY_MAKER_PERMISSIONS.PIPELINE_VIEW,
      POLICY_MAKER_PERMISSIONS.RISK_VIEW,
      POLICY_MAKER_PERMISSIONS.FINANCE_VIEW,
      POLICY_MAKER_PERMISSIONS.MEETINGS_VIEW,
      POLICY_MAKER_PERMISSIONS.MOM_VIEW,
      POLICY_MAKER_PERMISSIONS.DIRECTIVES_VIEW,
      POLICY_MAKER_PERMISSIONS.BOTTLENECK_VIEW,
      POLICY_MAKER_PERMISSIONS.RR_VIEW,
      POLICY_MAKER_PERMISSIONS.SOCIAL_AUDIT_VIEW,
      POLICY_MAKER_PERMISSIONS.REPORTS_VIEW,
      POLICY_MAKER_PERMISSIONS.PROJECT_DETAILS_VIEW,
      POLICY_MAKER_PERMISSIONS.DOCUMENTS_VIEW,
      POLICY_MAKER_PERMISSIONS.MOM_SIGN,
      POLICY_MAKER_PERMISSIONS.DIRECTIVE_ISSUE,
      POLICY_MAKER_PERMISSIONS.BOTTLENECK_ESCALATE,
      POLICY_MAKER_PERMISSIONS.REPORT_EXPORT,
      POLICY_MAKER_PERMISSIONS.NOTE_ADD
    ]
  },
  PROJECT_RR: {
    id: 'PROJECT_RR',
    name: 'Project R&R Committee',
    title: 'Project R&R Committee (PRJ-2026-GJ05)',
    legalBasis: 'RFCTLARR Act 2013, Section 45 (Trigger: Acquisitions >= 100 Acres)',
    scope: 'PROJECT',
    defaultProjectId: 'PRJ-2026-GJ05',
    badgeText: 'PROJECT R&R COMM (SEC 45)',
    badgeColor: 'bg-amber-900/50 text-amber-200 border-amber-500/50',
    head: 'District Collector, Anand & Ahmedabad',
    membersDescription: 'Local MP, MLA, Administrator R&R, SC/ST Reps, Women Rep, NGO, Lead Bank Reps',
    permissions: [
      POLICY_MAKER_PERMISSIONS.EXECUTIVE_OVERVIEW_VIEW,
      POLICY_MAKER_PERMISSIONS.GIS_VIEW,
      POLICY_MAKER_PERMISSIONS.PIPELINE_VIEW,
      POLICY_MAKER_PERMISSIONS.RISK_VIEW,
      POLICY_MAKER_PERMISSIONS.MEETINGS_VIEW,
      POLICY_MAKER_PERMISSIONS.MOM_VIEW,
      POLICY_MAKER_PERMISSIONS.DIRECTIVES_VIEW,
      POLICY_MAKER_PERMISSIONS.BOTTLENECK_VIEW,
      POLICY_MAKER_PERMISSIONS.RR_VIEW,
      POLICY_MAKER_PERMISSIONS.SOCIAL_AUDIT_VIEW,
      POLICY_MAKER_PERMISSIONS.REPORTS_VIEW,
      POLICY_MAKER_PERMISSIONS.PROJECT_DETAILS_VIEW,
      POLICY_MAKER_PERMISSIONS.DOCUMENTS_VIEW,
      POLICY_MAKER_PERMISSIONS.NOTE_ADD,
      POLICY_MAKER_PERMISSIONS.REPORT_EXPORT
    ]
  }
};

export function hasPolicyMakerPermission(roleId, permissionKey) {
  const role = COMMITTEE_ROLES[roleId];
  if (!role) return false;
  return role.permissions.includes(permissionKey);
}
