/**
 * NLAMS - Role-Based Access Control and Statutory Permissions
 */

export const DESIGNATION_ROLES = {
  GM_LAND: 'GM_LAND_REQUISITION',
  PROJECT_DIRECTOR: 'PROJECT_DIRECTOR_PIU',
  CALA_COLLECTOR: 'COMPETENT_AUTHORITY_LAND_ACQUISITION',
  LAO: 'LAND_ACQUISITION_OFFICER',
  GIS_ENGINEER: 'CHIEF_GIS_SURVEYOR',
  TREASURY_OFFICER: 'ESCROW_TREASURY_OFFICER'
};

export function hasPermission(userRole, action) {
  const permissions = {
    [DESIGNATION_ROLES.GM_LAND]: ['DRAFT_FORM_I', 'E_SIGN', 'ESCROW_APPROVE', 'HEARING_RESPONSE', 'GIS_EDIT', 'GAZETTE_EXPORT'],
    [DESIGNATION_ROLES.PROJECT_DIRECTOR]: ['DRAFT_FORM_I', 'ESCROW_APPROVE', 'HEARING_RESPONSE', 'GIS_EDIT', 'GAZETTE_EXPORT'],
    [DESIGNATION_ROLES.CALA_COLLECTOR]: ['HEARING_ADJUDICATE', 'AWARD_DETERMINE', 'GAZETTE_ISSUE', 'POSSESSION_ORDER'],
    [DESIGNATION_ROLES.GIS_ENGINEER]: ['GIS_EDIT', 'ULPIN_LINK', 'ALIGNMENT_UPLOAD']
  };

  return permissions[userRole]?.includes(action) ?? false;
}
